version: '3.3'

networks:
  web:
    driver: bridge

services:
  db:
    image: postgres
    hostname: db
    # container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    # ports:
      # - "5432:5432"
    network_mode: host
    restart: unless-stopped

  chrome:
    image: selenium/standalone-chrome-debug
    # Debug version enables VNC ability
    environment:
      - NODE_MAX_INSTANCES=5
      - SE_DRAIN_AFTER_SESSION_COUNT=5
      - NODE_MAX_SESSION=5
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      - SCALE=4
    shm_size: 4g
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
      - ./config/chrome_profile:/home/seluser/chrome_profile
    ports:
      - '4444:4444'
      - '5900:5900'
      # Bind selenium port & VNC port
    logging:
      driver: none
      # Disable noisy logs.

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres: