:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 10
staging:
  :concurrency: 2
development:
  :concurrency: 3
:queues:
  - [default, 3]
  - [discounts_import, 5]
  - [check_discounts, 1]
  - [product_parsing, 1]
