:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 5
staging:
  :concurrency: 1
development:
  :concurrency: 1
:queues:
  - [default, 3]
  - [discounts_import, 5]
  - [check_discounts, 5]
  - [product_parsing, 5]
