---
- hosts: all
  become: true

  vars_files:
    - app-vars.yml
  
  roles: 
    - role: common
    - role: user
    - role: ssh
    - role: ruby
      tags: ruby
    - role: nodejs
      tags: nodejs
    - role: yarn
      tags: nodejs
    - role: java
      tags: java
    - role: google-chrome
      tags: google-chrome
    - role: chromedriver
      tags: chromedriver
    - role: selenium
      tags: selenium
    - role: postgresql
      tags: postgresql
    - role: redis
      tags: redis
    - role: nginx
      tags: nginx
    - role: logrotate
      tags: logrotate